export const Users = [
  {
    id:1,
    profilePicture: "assets/person/yamuna ghat.jpg",
    username: "Saif",
  },
  {
    id:2,
    profilePicture: "assets/person/tourism.jpg",
    username: "Kunal",
  },
  {
    id:3,
    profilePicture: "assets/person/kashmir 10.jpg",
    username: "Alex",
  },
  {
    id:4,
    profilePicture: "assets/person/Dzukou vally Nagaland.jpg",
    username: "Danish",
  },
  {
    id: 5,
    photo: "assets/post/kashmir 2.jpg",
    username: "Arbaz",
  },

];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/delhi.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/amritsar.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/hyderabad.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/kashmir 2.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  // {
  //   id: 6,
  //   photo: "assets/post/kashmir 3.jpg",
  //   date: "1 day ago",
  //   userId: 6,
  //   like: 44,
  //   comment: 6,
  // },
  // {
  //   id: 7,
  //   desc: "Never regret anything that made you smile.",
  //   photo: "assets/post/kashmir 1.jpg",
  //   date: "2 days ago",
  //   userId: 7,
  //   like: 52,
  //   comment: 3,
  // },
  // {
  //   id: 8,
  //   photo: "assets/post/kashmir 8.jpg",
  //   date: "3 days ago",
  //   userId: 8,
  //   like: 15,
  //   comment: 1,
  // },
  // {
  //   id: 9,
  //   desc: "Change the world by being yourself.",
  //   photo: "assets/post/kerala 1.jpg",
  //   date: "5 days ago",
  //   userId: 9,
  //   like: 11,
  //   comment: 2,
  // },
  // {
  //   id: 10,
  //   photo: "assets/post/kolkata.jpg",
  //   date: "1 week ago",
  //   userId: 10,
  //   like: 104,
  //   comment: 12,
  // },
];
